name: ai-ci

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker build
        run: docker build -t ${{ secrets.DOCKER_USER }}/project-01-ai:${{ github.sha }} .

      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: Push image
        run: docker push ${{ secrets.DOCKER_USER }}/project-01-ai:${{ github.sha }}

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1

      - name: Checkout kustomize repository
        uses: actions/checkout@v2
        with:
          repository: ibm3-Peachtree/k8s-manifest-repo
          ref: master
          token: "${{ secrets.ACTION_TOKEN }}"
          path: k8s-repo

      - name: Update image tag in k8s repo
        run: |
          cd k8s-repo/ai
          sed -i "s|image: .*|image: ${{ secrets.DOCKER_USER }}/project-01-ai:${{ github.sha }}|" 1.ai-deployment.yml
          cat 1.ai-deployment.yml

      - name: Commit files
        run: |
          cd k8s-repo
          git config user.email "github-actions@github.com"
          git config user.name "github-actions"
          git add .
          git commit -m "Update ai image tag to ${{ github.sha }}" || echo "No changes to commit"
          git push origin master
